name = "InfluxDBClient"
uuid = "7a087161-7d97-4627-bbdd-0c82161d9408"
authors = ["bernhard.koenig", "marius.kruger"]
version = "0.0.8"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CodecZlib = "944b1d66-785c-5afd-91f1-9de20f533193"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
TimeZones = "f269a46b-ccf7-5d73-abea-4c690281aa53"
UnPack = "3a884ed6-31ef-47d7-9d2a-63182c4928ed"

[compat]
julia >= "1.6"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "StatsBase", "Aqua"]
